//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace otel_otomasyonu.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("otel_otomasyonu.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap kaya_palazzo_golf {
            get {
                object obj = ResourceManager.GetObject("kaya-palazzo-golf", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap mirage_park_resort_genel_3af754be_e7f8_4ccc_aa87_d9890f425721 {
            get {
                object obj = ResourceManager.GetObject("mirage-park-resort-genel-3af754be-e7f8-4ccc-aa87-d9890f425721", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap mirage_park_resort_genel_3af754be_e7f8_4ccc_aa87_d9890f4257211 {
            get {
                object obj = ResourceManager.GetObject("mirage-park-resort-genel-3af754be-e7f8-4ccc-aa87-d9890f4257211", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap mirage_park_resort_genel_9939c935_967d_4c59_8495_0c60f4715333 {
            get {
                object obj = ResourceManager.GetObject("mirage-park-resort-genel-9939c935-967d-4c59-8495-0c60f4715333", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap mirage_park_resort_plaj_ve_havuz_217e3e62_79f8_4c4e_955e_85cc0f67b2e7 {
            get {
                object obj = ResourceManager.GetObject("mirage-park-resort-plaj-ve-havuz-217e3e62-79f8-4c4e-955e-85cc0f67b2e7", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap mirage_park_resort_plaj_ve_havuz_3bab2e97_9ebb_4550_bb74_5f1d254b4682 {
            get {
                object obj = ResourceManager.GetObject("mirage-park-resort-plaj-ve-havuz-3bab2e97-9ebb-4550-bb74-5f1d254b4682", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap mirage_park_resort_plaj_ve_havuz_3bab2e97_9ebb_4550_bb74_5f1d254b46821 {
            get {
                object obj = ResourceManager.GetObject("mirage-park-resort-plaj-ve-havuz-3bab2e97-9ebb-4550-bb74-5f1d254b46821", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap mirage_park_resort_plaj_ve_havuz_4b3db910_872f_49e6_b6d9_badc7421b71a {
            get {
                object obj = ResourceManager.GetObject("mirage-park-resort-plaj-ve-havuz-4b3db910-872f-49e6-b6d9-badc7421b71a", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap mirage_park_resort_plaj_ve_havuz_ce6d1c0a_df97_4e4c_a38b_e80302c03c47 {
            get {
                object obj = ResourceManager.GetObject("mirage-park-resort-plaj-ve-havuz-ce6d1c0a-df97-4e4c-a38b-e80302c03c47", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
